/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Demo API
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from '@tanstack/react-query';

import type { OrderRequest, OrderResponse, ProblemDetails } from '.././model';

import { axiosInstance } from '../../axiosInstance';
import type { ErrorType, BodyType } from '../../axiosInstance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const orderGetAll = (
	options?: SecondParameter<typeof axiosInstance>,
	signal?: AbortSignal
) => {
	return axiosInstance<OrderResponse[]>(
		{ url: `/Order`, method: 'GET', signal },
		options
	);
};

export const getOrderGetAllQueryKey = () => {
	return [`/Order`] as const;
};

export const getOrderGetAllQueryOptions = <
	TData = Awaited<ReturnType<typeof orderGetAll>>,
	TError = ErrorType<void>,
>(options?: {
	query?: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof orderGetAll>>, TError, TData>
	>;
	request?: SecondParameter<typeof axiosInstance>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getOrderGetAllQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof orderGetAll>>> = ({
		signal,
	}) => orderGetAll(requestOptions, signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof orderGetAll>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type OrderGetAllQueryResult = NonNullable<
	Awaited<ReturnType<typeof orderGetAll>>
>;
export type OrderGetAllQueryError = ErrorType<void>;

export function useOrderGetAll<
	TData = Awaited<ReturnType<typeof orderGetAll>>,
	TError = ErrorType<void>,
>(
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof orderGetAll>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof orderGetAll>>,
					TError,
					Awaited<ReturnType<typeof orderGetAll>>
				>,
				'initialData'
			>;
		request?: SecondParameter<typeof axiosInstance>;
	},
	queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useOrderGetAll<
	TData = Awaited<ReturnType<typeof orderGetAll>>,
	TError = ErrorType<void>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof orderGetAll>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof orderGetAll>>,
					TError,
					Awaited<ReturnType<typeof orderGetAll>>
				>,
				'initialData'
			>;
		request?: SecondParameter<typeof axiosInstance>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useOrderGetAll<
	TData = Awaited<ReturnType<typeof orderGetAll>>,
	TError = ErrorType<void>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof orderGetAll>>, TError, TData>
		>;
		request?: SecondParameter<typeof axiosInstance>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};

export function useOrderGetAll<
	TData = Awaited<ReturnType<typeof orderGetAll>>,
	TError = ErrorType<void>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof orderGetAll>>, TError, TData>
		>;
		request?: SecondParameter<typeof axiosInstance>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getOrderGetAllQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

export const orderCreate = (
	orderRequest: BodyType<OrderRequest>,
	options?: SecondParameter<typeof axiosInstance>,
	signal?: AbortSignal
) => {
	return axiosInstance<OrderResponse>(
		{
			url: `/Order`,
			method: 'POST',
			headers: { 'Content-Type': 'application/json' },
			data: orderRequest,
			signal,
		},
		options
	);
};

export const getOrderCreateMutationOptions = <
	TError = ErrorType<ProblemDetails | void>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof orderCreate>>,
		TError,
		{ data: BodyType<OrderRequest> },
		TContext
	>;
	request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof orderCreate>>,
	TError,
	{ data: BodyType<OrderRequest> },
	TContext
> => {
	const mutationKey = ['orderCreate'];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			'mutationKey' in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof orderCreate>>,
		{ data: BodyType<OrderRequest> }
	> = props => {
		const { data } = props ?? {};

		return orderCreate(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type OrderCreateMutationResult = NonNullable<
	Awaited<ReturnType<typeof orderCreate>>
>;
export type OrderCreateMutationBody = BodyType<OrderRequest>;
export type OrderCreateMutationError = ErrorType<ProblemDetails | void>;

export const useOrderCreate = <
	TError = ErrorType<ProblemDetails | void>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof orderCreate>>,
			TError,
			{ data: BodyType<OrderRequest> },
			TContext
		>;
		request?: SecondParameter<typeof axiosInstance>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof orderCreate>>,
	TError,
	{ data: BodyType<OrderRequest> },
	TContext
> => {
	return useMutation(getOrderCreateMutationOptions(options), queryClient);
};
export const orderGetById = (
	id: string,
	options?: SecondParameter<typeof axiosInstance>,
	signal?: AbortSignal
) => {
	return axiosInstance<OrderResponse>(
		{ url: `/Order/${id}`, method: 'GET', signal },
		options
	);
};

export const getOrderGetByIdQueryKey = (id: string) => {
	return [`/Order/${id}`] as const;
};

export const getOrderGetByIdQueryOptions = <
	TData = Awaited<ReturnType<typeof orderGetById>>,
	TError = ErrorType<ProblemDetails | void>,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof orderGetById>>, TError, TData>
		>;
		request?: SecondParameter<typeof axiosInstance>;
	}
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getOrderGetByIdQueryKey(id);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof orderGetById>>> = ({
		signal,
	}) => orderGetById(id, requestOptions, signal);

	return {
		queryKey,
		queryFn,
		enabled: !!id,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof orderGetById>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type OrderGetByIdQueryResult = NonNullable<
	Awaited<ReturnType<typeof orderGetById>>
>;
export type OrderGetByIdQueryError = ErrorType<ProblemDetails | void>;

export function useOrderGetById<
	TData = Awaited<ReturnType<typeof orderGetById>>,
	TError = ErrorType<ProblemDetails | void>,
>(
	id: string,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof orderGetById>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof orderGetById>>,
					TError,
					Awaited<ReturnType<typeof orderGetById>>
				>,
				'initialData'
			>;
		request?: SecondParameter<typeof axiosInstance>;
	},
	queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useOrderGetById<
	TData = Awaited<ReturnType<typeof orderGetById>>,
	TError = ErrorType<ProblemDetails | void>,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof orderGetById>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof orderGetById>>,
					TError,
					Awaited<ReturnType<typeof orderGetById>>
				>,
				'initialData'
			>;
		request?: SecondParameter<typeof axiosInstance>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useOrderGetById<
	TData = Awaited<ReturnType<typeof orderGetById>>,
	TError = ErrorType<ProblemDetails | void>,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof orderGetById>>, TError, TData>
		>;
		request?: SecondParameter<typeof axiosInstance>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};

export function useOrderGetById<
	TData = Awaited<ReturnType<typeof orderGetById>>,
	TError = ErrorType<ProblemDetails | void>,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof orderGetById>>, TError, TData>
		>;
		request?: SecondParameter<typeof axiosInstance>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getOrderGetByIdQueryOptions(id, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

export const orderDelete = (
	id: string,
	options?: SecondParameter<typeof axiosInstance>,
	signal?: AbortSignal
) => {
	return axiosInstance<void>(
		{ url: `/Order/${id}`, method: 'DELETE', signal },
		options
	);
};

export const getOrderDeleteMutationOptions = <
	TError = ErrorType<ProblemDetails | void>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof orderDelete>>,
		TError,
		{ id: string },
		TContext
	>;
	request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof orderDelete>>,
	TError,
	{ id: string },
	TContext
> => {
	const mutationKey = ['orderDelete'];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			'mutationKey' in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof orderDelete>>,
		{ id: string }
	> = props => {
		const { id } = props ?? {};

		return orderDelete(id, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type OrderDeleteMutationResult = NonNullable<
	Awaited<ReturnType<typeof orderDelete>>
>;

export type OrderDeleteMutationError = ErrorType<ProblemDetails | void>;

export const useOrderDelete = <
	TError = ErrorType<ProblemDetails | void>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof orderDelete>>,
			TError,
			{ id: string },
			TContext
		>;
		request?: SecondParameter<typeof axiosInstance>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof orderDelete>>,
	TError,
	{ id: string },
	TContext
> => {
	return useMutation(getOrderDeleteMutationOptions(options), queryClient);
};
