/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Demo API
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from '@tanstack/react-query';

import type {
	ProblemDetails,
	RegisterUserRequest,
	UserResponse,
} from '.././model';

import { axiosInstance } from '../../axiosInstance';
import type { ErrorType, BodyType } from '../../axiosInstance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const userGetSelf = (
	options?: SecondParameter<typeof axiosInstance>,
	signal?: AbortSignal
) => {
	return axiosInstance<UserResponse>(
		{ url: `/User`, method: 'GET', signal },
		options
	);
};

export const getUserGetSelfQueryKey = () => {
	return [`/User`] as const;
};

export const getUserGetSelfQueryOptions = <
	TData = Awaited<ReturnType<typeof userGetSelf>>,
	TError = ErrorType<ProblemDetails | void>,
>(options?: {
	query?: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof userGetSelf>>, TError, TData>
	>;
	request?: SecondParameter<typeof axiosInstance>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getUserGetSelfQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof userGetSelf>>> = ({
		signal,
	}) => userGetSelf(requestOptions, signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof userGetSelf>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type UserGetSelfQueryResult = NonNullable<
	Awaited<ReturnType<typeof userGetSelf>>
>;
export type UserGetSelfQueryError = ErrorType<ProblemDetails | void>;

export function useUserGetSelf<
	TData = Awaited<ReturnType<typeof userGetSelf>>,
	TError = ErrorType<ProblemDetails | void>,
>(
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof userGetSelf>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof userGetSelf>>,
					TError,
					Awaited<ReturnType<typeof userGetSelf>>
				>,
				'initialData'
			>;
		request?: SecondParameter<typeof axiosInstance>;
	},
	queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUserGetSelf<
	TData = Awaited<ReturnType<typeof userGetSelf>>,
	TError = ErrorType<ProblemDetails | void>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof userGetSelf>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof userGetSelf>>,
					TError,
					Awaited<ReturnType<typeof userGetSelf>>
				>,
				'initialData'
			>;
		request?: SecondParameter<typeof axiosInstance>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUserGetSelf<
	TData = Awaited<ReturnType<typeof userGetSelf>>,
	TError = ErrorType<ProblemDetails | void>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof userGetSelf>>, TError, TData>
		>;
		request?: SecondParameter<typeof axiosInstance>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};

export function useUserGetSelf<
	TData = Awaited<ReturnType<typeof userGetSelf>>,
	TError = ErrorType<ProblemDetails | void>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof userGetSelf>>, TError, TData>
		>;
		request?: SecondParameter<typeof axiosInstance>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getUserGetSelfQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

export const userDelete = (
	options?: SecondParameter<typeof axiosInstance>,
	signal?: AbortSignal
) => {
	return axiosInstance<void>(
		{ url: `/User`, method: 'DELETE', signal },
		options
	);
};

export const getUserDeleteMutationOptions = <
	TError = ErrorType<ProblemDetails | void>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof userDelete>>,
		TError,
		void,
		TContext
	>;
	request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof userDelete>>,
	TError,
	void,
	TContext
> => {
	const mutationKey = ['userDelete'];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			'mutationKey' in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof userDelete>>,
		void
	> = () => {
		return userDelete(requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type UserDeleteMutationResult = NonNullable<
	Awaited<ReturnType<typeof userDelete>>
>;

export type UserDeleteMutationError = ErrorType<ProblemDetails | void>;

export const useUserDelete = <
	TError = ErrorType<ProblemDetails | void>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof userDelete>>,
			TError,
			void,
			TContext
		>;
		request?: SecondParameter<typeof axiosInstance>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof userDelete>>,
	TError,
	void,
	TContext
> => {
	return useMutation(getUserDeleteMutationOptions(options), queryClient);
};
export const userRegister = (
	registerUserRequest: BodyType<RegisterUserRequest>,
	options?: SecondParameter<typeof axiosInstance>,
	signal?: AbortSignal
) => {
	return axiosInstance<UserResponse>(
		{
			url: `/User/register`,
			method: 'POST',
			headers: { 'Content-Type': 'application/json' },
			data: registerUserRequest,
			signal,
		},
		options
	);
};

export const getUserRegisterMutationOptions = <
	TError = ErrorType<ProblemDetails | void>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof userRegister>>,
		TError,
		{ data: BodyType<RegisterUserRequest> },
		TContext
	>;
	request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof userRegister>>,
	TError,
	{ data: BodyType<RegisterUserRequest> },
	TContext
> => {
	const mutationKey = ['userRegister'];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			'mutationKey' in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof userRegister>>,
		{ data: BodyType<RegisterUserRequest> }
	> = props => {
		const { data } = props ?? {};

		return userRegister(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type UserRegisterMutationResult = NonNullable<
	Awaited<ReturnType<typeof userRegister>>
>;
export type UserRegisterMutationBody = BodyType<RegisterUserRequest>;
export type UserRegisterMutationError = ErrorType<ProblemDetails | void>;

export const useUserRegister = <
	TError = ErrorType<ProblemDetails | void>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof userRegister>>,
			TError,
			{ data: BodyType<RegisterUserRequest> },
			TContext
		>;
		request?: SecondParameter<typeof axiosInstance>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof userRegister>>,
	TError,
	{ data: BodyType<RegisterUserRequest> },
	TContext
> => {
	return useMutation(getUserRegisterMutationOptions(options), queryClient);
};
export const userGrantAdminRole = (
	email: string,
	options?: SecondParameter<typeof axiosInstance>,
	signal?: AbortSignal
) => {
	return axiosInstance<void>(
		{ url: `/User/grantAdminRole/${email}`, method: 'PATCH', signal },
		options
	);
};

export const getUserGrantAdminRoleMutationOptions = <
	TError = ErrorType<ProblemDetails | void>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof userGrantAdminRole>>,
		TError,
		{ email: string },
		TContext
	>;
	request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof userGrantAdminRole>>,
	TError,
	{ email: string },
	TContext
> => {
	const mutationKey = ['userGrantAdminRole'];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			'mutationKey' in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof userGrantAdminRole>>,
		{ email: string }
	> = props => {
		const { email } = props ?? {};

		return userGrantAdminRole(email, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type UserGrantAdminRoleMutationResult = NonNullable<
	Awaited<ReturnType<typeof userGrantAdminRole>>
>;

export type UserGrantAdminRoleMutationError = ErrorType<ProblemDetails | void>;

export const useUserGrantAdminRole = <
	TError = ErrorType<ProblemDetails | void>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof userGrantAdminRole>>,
			TError,
			{ email: string },
			TContext
		>;
		request?: SecondParameter<typeof axiosInstance>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof userGrantAdminRole>>,
	TError,
	{ email: string },
	TContext
> => {
	return useMutation(
		getUserGrantAdminRoleMutationOptions(options),
		queryClient
	);
};
export const userRemoveAdminRole = (
	email: string,
	options?: SecondParameter<typeof axiosInstance>,
	signal?: AbortSignal
) => {
	return axiosInstance<void>(
		{ url: `/User/removeAdminRole/${email}`, method: 'PATCH', signal },
		options
	);
};

export const getUserRemoveAdminRoleMutationOptions = <
	TError = ErrorType<ProblemDetails | void>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof userRemoveAdminRole>>,
		TError,
		{ email: string },
		TContext
	>;
	request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof userRemoveAdminRole>>,
	TError,
	{ email: string },
	TContext
> => {
	const mutationKey = ['userRemoveAdminRole'];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			'mutationKey' in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof userRemoveAdminRole>>,
		{ email: string }
	> = props => {
		const { email } = props ?? {};

		return userRemoveAdminRole(email, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type UserRemoveAdminRoleMutationResult = NonNullable<
	Awaited<ReturnType<typeof userRemoveAdminRole>>
>;

export type UserRemoveAdminRoleMutationError = ErrorType<ProblemDetails | void>;

export const useUserRemoveAdminRole = <
	TError = ErrorType<ProblemDetails | void>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof userRemoveAdminRole>>,
			TError,
			{ email: string },
			TContext
		>;
		request?: SecondParameter<typeof axiosInstance>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof userRemoveAdminRole>>,
	TError,
	{ email: string },
	TContext
> => {
	return useMutation(
		getUserRemoveAdminRoleMutationOptions(options),
		queryClient
	);
};
