/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Demo API
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from '@tanstack/react-query';

import type { ProblemDetails, RegisterUser, UserResponse } from '.././model';

import { axiosInstance } from '../../axiosInstance';
import type { ErrorType, BodyType } from '../../axiosInstance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const userGetById = (
	id: string,
	options?: SecondParameter<typeof axiosInstance>,
	signal?: AbortSignal
) => {
	return axiosInstance<UserResponse>(
		{ url: `/User/${id}`, method: 'GET', signal },
		options
	);
};

export const getUserGetByIdQueryKey = (id: string) => {
	return [`/User/${id}`] as const;
};

export const getUserGetByIdQueryOptions = <
	TData = Awaited<ReturnType<typeof userGetById>>,
	TError = ErrorType<ProblemDetails | void>,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof userGetById>>, TError, TData>
		>;
		request?: SecondParameter<typeof axiosInstance>;
	}
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getUserGetByIdQueryKey(id);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof userGetById>>> = ({
		signal,
	}) => userGetById(id, requestOptions, signal);

	return {
		queryKey,
		queryFn,
		enabled: !!id,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof userGetById>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type UserGetByIdQueryResult = NonNullable<
	Awaited<ReturnType<typeof userGetById>>
>;
export type UserGetByIdQueryError = ErrorType<ProblemDetails | void>;

export function useUserGetById<
	TData = Awaited<ReturnType<typeof userGetById>>,
	TError = ErrorType<ProblemDetails | void>,
>(
	id: string,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof userGetById>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof userGetById>>,
					TError,
					Awaited<ReturnType<typeof userGetById>>
				>,
				'initialData'
			>;
		request?: SecondParameter<typeof axiosInstance>;
	},
	queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUserGetById<
	TData = Awaited<ReturnType<typeof userGetById>>,
	TError = ErrorType<ProblemDetails | void>,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof userGetById>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof userGetById>>,
					TError,
					Awaited<ReturnType<typeof userGetById>>
				>,
				'initialData'
			>;
		request?: SecondParameter<typeof axiosInstance>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUserGetById<
	TData = Awaited<ReturnType<typeof userGetById>>,
	TError = ErrorType<ProblemDetails | void>,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof userGetById>>, TError, TData>
		>;
		request?: SecondParameter<typeof axiosInstance>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};

export function useUserGetById<
	TData = Awaited<ReturnType<typeof userGetById>>,
	TError = ErrorType<ProblemDetails | void>,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof userGetById>>, TError, TData>
		>;
		request?: SecondParameter<typeof axiosInstance>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getUserGetByIdQueryOptions(id, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

export const userDelete = (
	id: string,
	options?: SecondParameter<typeof axiosInstance>,
	signal?: AbortSignal
) => {
	return axiosInstance<void>(
		{ url: `/User/${id}`, method: 'DELETE', signal },
		options
	);
};

export const getUserDeleteMutationOptions = <
	TError = ErrorType<ProblemDetails | void>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof userDelete>>,
		TError,
		{ id: string },
		TContext
	>;
	request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof userDelete>>,
	TError,
	{ id: string },
	TContext
> => {
	const mutationKey = ['userDelete'];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			'mutationKey' in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof userDelete>>,
		{ id: string }
	> = props => {
		const { id } = props ?? {};

		return userDelete(id, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type UserDeleteMutationResult = NonNullable<
	Awaited<ReturnType<typeof userDelete>>
>;

export type UserDeleteMutationError = ErrorType<ProblemDetails | void>;

export const useUserDelete = <
	TError = ErrorType<ProblemDetails | void>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof userDelete>>,
			TError,
			{ id: string },
			TContext
		>;
		request?: SecondParameter<typeof axiosInstance>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof userDelete>>,
	TError,
	{ id: string },
	TContext
> => {
	return useMutation(getUserDeleteMutationOptions(options), queryClient);
};
export const userGetByFirebaseUid = (
	firebaseUid: string,
	options?: SecondParameter<typeof axiosInstance>,
	signal?: AbortSignal
) => {
	return axiosInstance<UserResponse>(
		{ url: `/User/getByFirebaseUid/${firebaseUid}`, method: 'GET', signal },
		options
	);
};

export const getUserGetByFirebaseUidQueryKey = (firebaseUid: string) => {
	return [`/User/getByFirebaseUid/${firebaseUid}`] as const;
};

export const getUserGetByFirebaseUidQueryOptions = <
	TData = Awaited<ReturnType<typeof userGetByFirebaseUid>>,
	TError = ErrorType<ProblemDetails | void>,
>(
	firebaseUid: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof userGetByFirebaseUid>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof axiosInstance>;
	}
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getUserGetByFirebaseUidQueryKey(firebaseUid);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof userGetByFirebaseUid>>
	> = ({ signal }) =>
		userGetByFirebaseUid(firebaseUid, requestOptions, signal);

	return {
		queryKey,
		queryFn,
		enabled: !!firebaseUid,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof userGetByFirebaseUid>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type UserGetByFirebaseUidQueryResult = NonNullable<
	Awaited<ReturnType<typeof userGetByFirebaseUid>>
>;
export type UserGetByFirebaseUidQueryError = ErrorType<ProblemDetails | void>;

export function useUserGetByFirebaseUid<
	TData = Awaited<ReturnType<typeof userGetByFirebaseUid>>,
	TError = ErrorType<ProblemDetails | void>,
>(
	firebaseUid: string,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof userGetByFirebaseUid>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof userGetByFirebaseUid>>,
					TError,
					Awaited<ReturnType<typeof userGetByFirebaseUid>>
				>,
				'initialData'
			>;
		request?: SecondParameter<typeof axiosInstance>;
	},
	queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUserGetByFirebaseUid<
	TData = Awaited<ReturnType<typeof userGetByFirebaseUid>>,
	TError = ErrorType<ProblemDetails | void>,
>(
	firebaseUid: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof userGetByFirebaseUid>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof userGetByFirebaseUid>>,
					TError,
					Awaited<ReturnType<typeof userGetByFirebaseUid>>
				>,
				'initialData'
			>;
		request?: SecondParameter<typeof axiosInstance>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUserGetByFirebaseUid<
	TData = Awaited<ReturnType<typeof userGetByFirebaseUid>>,
	TError = ErrorType<ProblemDetails | void>,
>(
	firebaseUid: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof userGetByFirebaseUid>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof axiosInstance>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};

export function useUserGetByFirebaseUid<
	TData = Awaited<ReturnType<typeof userGetByFirebaseUid>>,
	TError = ErrorType<ProblemDetails | void>,
>(
	firebaseUid: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof userGetByFirebaseUid>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof axiosInstance>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getUserGetByFirebaseUidQueryOptions(
		firebaseUid,
		options
	);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

export const userRegister = (
	registerUser: BodyType<RegisterUser>,
	options?: SecondParameter<typeof axiosInstance>,
	signal?: AbortSignal
) => {
	return axiosInstance<UserResponse>(
		{
			url: `/User/register`,
			method: 'POST',
			headers: { 'Content-Type': 'application/json' },
			data: registerUser,
			signal,
		},
		options
	);
};

export const getUserRegisterMutationOptions = <
	TError = ErrorType<ProblemDetails | void>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof userRegister>>,
		TError,
		{ data: BodyType<RegisterUser> },
		TContext
	>;
	request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof userRegister>>,
	TError,
	{ data: BodyType<RegisterUser> },
	TContext
> => {
	const mutationKey = ['userRegister'];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			'mutationKey' in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof userRegister>>,
		{ data: BodyType<RegisterUser> }
	> = props => {
		const { data } = props ?? {};

		return userRegister(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type UserRegisterMutationResult = NonNullable<
	Awaited<ReturnType<typeof userRegister>>
>;
export type UserRegisterMutationBody = BodyType<RegisterUser>;
export type UserRegisterMutationError = ErrorType<ProblemDetails | void>;

export const useUserRegister = <
	TError = ErrorType<ProblemDetails | void>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof userRegister>>,
			TError,
			{ data: BodyType<RegisterUser> },
			TContext
		>;
		request?: SecondParameter<typeof axiosInstance>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof userRegister>>,
	TError,
	{ data: BodyType<RegisterUser> },
	TContext
> => {
	return useMutation(getUserRegisterMutationOptions(options), queryClient);
};
export const userGrantAdminRole = (
	email: string,
	options?: SecondParameter<typeof axiosInstance>,
	signal?: AbortSignal
) => {
	return axiosInstance<void>(
		{ url: `/User/grantAdminRole/${email}`, method: 'PATCH', signal },
		options
	);
};

export const getUserGrantAdminRoleMutationOptions = <
	TError = ErrorType<ProblemDetails | void>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof userGrantAdminRole>>,
		TError,
		{ email: string },
		TContext
	>;
	request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof userGrantAdminRole>>,
	TError,
	{ email: string },
	TContext
> => {
	const mutationKey = ['userGrantAdminRole'];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			'mutationKey' in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof userGrantAdminRole>>,
		{ email: string }
	> = props => {
		const { email } = props ?? {};

		return userGrantAdminRole(email, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type UserGrantAdminRoleMutationResult = NonNullable<
	Awaited<ReturnType<typeof userGrantAdminRole>>
>;

export type UserGrantAdminRoleMutationError = ErrorType<ProblemDetails | void>;

export const useUserGrantAdminRole = <
	TError = ErrorType<ProblemDetails | void>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof userGrantAdminRole>>,
			TError,
			{ email: string },
			TContext
		>;
		request?: SecondParameter<typeof axiosInstance>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof userGrantAdminRole>>,
	TError,
	{ email: string },
	TContext
> => {
	return useMutation(
		getUserGrantAdminRoleMutationOptions(options),
		queryClient
	);
};
export const userRemoveAdminRole = (
	email: string,
	options?: SecondParameter<typeof axiosInstance>,
	signal?: AbortSignal
) => {
	return axiosInstance<void>(
		{ url: `/User/removeAdminRole/${email}`, method: 'PATCH', signal },
		options
	);
};

export const getUserRemoveAdminRoleMutationOptions = <
	TError = ErrorType<ProblemDetails | void>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof userRemoveAdminRole>>,
		TError,
		{ email: string },
		TContext
	>;
	request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof userRemoveAdminRole>>,
	TError,
	{ email: string },
	TContext
> => {
	const mutationKey = ['userRemoveAdminRole'];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			'mutationKey' in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof userRemoveAdminRole>>,
		{ email: string }
	> = props => {
		const { email } = props ?? {};

		return userRemoveAdminRole(email, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type UserRemoveAdminRoleMutationResult = NonNullable<
	Awaited<ReturnType<typeof userRemoveAdminRole>>
>;

export type UserRemoveAdminRoleMutationError = ErrorType<ProblemDetails | void>;

export const useUserRemoveAdminRole = <
	TError = ErrorType<ProblemDetails | void>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof userRemoveAdminRole>>,
			TError,
			{ email: string },
			TContext
		>;
		request?: SecondParameter<typeof axiosInstance>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof userRemoveAdminRole>>,
	TError,
	{ email: string },
	TContext
> => {
	return useMutation(
		getUserRemoveAdminRoleMutationOptions(options),
		queryClient
	);
};
