/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Demo API
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from '@tanstack/react-query';

import type { ProblemDetails, ReviewRequest, ReviewResponse } from '.././model';

import { axiosInstance } from '../../axiosInstance';
import type { ErrorType, BodyType } from '../../axiosInstance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const reviewGetAll = (
	options?: SecondParameter<typeof axiosInstance>,
	signal?: AbortSignal
) => {
	return axiosInstance<ReviewResponse[]>(
		{ url: `/Review`, method: 'GET', signal },
		options
	);
};

export const getReviewGetAllQueryKey = () => {
	return [`/Review`] as const;
};

export const getReviewGetAllQueryOptions = <
	TData = Awaited<ReturnType<typeof reviewGetAll>>,
	TError = ErrorType<void>,
>(options?: {
	query?: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof reviewGetAll>>, TError, TData>
	>;
	request?: SecondParameter<typeof axiosInstance>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getReviewGetAllQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof reviewGetAll>>> = ({
		signal,
	}) => reviewGetAll(requestOptions, signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof reviewGetAll>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ReviewGetAllQueryResult = NonNullable<
	Awaited<ReturnType<typeof reviewGetAll>>
>;
export type ReviewGetAllQueryError = ErrorType<void>;

export function useReviewGetAll<
	TData = Awaited<ReturnType<typeof reviewGetAll>>,
	TError = ErrorType<void>,
>(
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof reviewGetAll>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof reviewGetAll>>,
					TError,
					Awaited<ReturnType<typeof reviewGetAll>>
				>,
				'initialData'
			>;
		request?: SecondParameter<typeof axiosInstance>;
	},
	queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useReviewGetAll<
	TData = Awaited<ReturnType<typeof reviewGetAll>>,
	TError = ErrorType<void>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof reviewGetAll>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof reviewGetAll>>,
					TError,
					Awaited<ReturnType<typeof reviewGetAll>>
				>,
				'initialData'
			>;
		request?: SecondParameter<typeof axiosInstance>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useReviewGetAll<
	TData = Awaited<ReturnType<typeof reviewGetAll>>,
	TError = ErrorType<void>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof reviewGetAll>>, TError, TData>
		>;
		request?: SecondParameter<typeof axiosInstance>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};

export function useReviewGetAll<
	TData = Awaited<ReturnType<typeof reviewGetAll>>,
	TError = ErrorType<void>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof reviewGetAll>>, TError, TData>
		>;
		request?: SecondParameter<typeof axiosInstance>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getReviewGetAllQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

export const reviewCreate = (
	reviewRequest: BodyType<ReviewRequest>,
	options?: SecondParameter<typeof axiosInstance>,
	signal?: AbortSignal
) => {
	return axiosInstance<void>(
		{
			url: `/Review`,
			method: 'POST',
			headers: { 'Content-Type': 'application/json' },
			data: reviewRequest,
			signal,
		},
		options
	);
};

export const getReviewCreateMutationOptions = <
	TError = ErrorType<ProblemDetails | void>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof reviewCreate>>,
		TError,
		{ data: BodyType<ReviewRequest> },
		TContext
	>;
	request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof reviewCreate>>,
	TError,
	{ data: BodyType<ReviewRequest> },
	TContext
> => {
	const mutationKey = ['reviewCreate'];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			'mutationKey' in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof reviewCreate>>,
		{ data: BodyType<ReviewRequest> }
	> = props => {
		const { data } = props ?? {};

		return reviewCreate(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type ReviewCreateMutationResult = NonNullable<
	Awaited<ReturnType<typeof reviewCreate>>
>;
export type ReviewCreateMutationBody = BodyType<ReviewRequest>;
export type ReviewCreateMutationError = ErrorType<ProblemDetails | void>;

export const useReviewCreate = <
	TError = ErrorType<ProblemDetails | void>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof reviewCreate>>,
			TError,
			{ data: BodyType<ReviewRequest> },
			TContext
		>;
		request?: SecondParameter<typeof axiosInstance>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof reviewCreate>>,
	TError,
	{ data: BodyType<ReviewRequest> },
	TContext
> => {
	return useMutation(getReviewCreateMutationOptions(options), queryClient);
};
export const reviewGetById = (
	id: string,
	options?: SecondParameter<typeof axiosInstance>,
	signal?: AbortSignal
) => {
	return axiosInstance<ReviewResponse>(
		{ url: `/Review/${id}`, method: 'GET', signal },
		options
	);
};

export const getReviewGetByIdQueryKey = (id: string) => {
	return [`/Review/${id}`] as const;
};

export const getReviewGetByIdQueryOptions = <
	TData = Awaited<ReturnType<typeof reviewGetById>>,
	TError = ErrorType<ProblemDetails | void>,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof reviewGetById>>, TError, TData>
		>;
		request?: SecondParameter<typeof axiosInstance>;
	}
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getReviewGetByIdQueryKey(id);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof reviewGetById>>> = ({
		signal,
	}) => reviewGetById(id, requestOptions, signal);

	return {
		queryKey,
		queryFn,
		enabled: !!id,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof reviewGetById>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ReviewGetByIdQueryResult = NonNullable<
	Awaited<ReturnType<typeof reviewGetById>>
>;
export type ReviewGetByIdQueryError = ErrorType<ProblemDetails | void>;

export function useReviewGetById<
	TData = Awaited<ReturnType<typeof reviewGetById>>,
	TError = ErrorType<ProblemDetails | void>,
>(
	id: string,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof reviewGetById>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof reviewGetById>>,
					TError,
					Awaited<ReturnType<typeof reviewGetById>>
				>,
				'initialData'
			>;
		request?: SecondParameter<typeof axiosInstance>;
	},
	queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useReviewGetById<
	TData = Awaited<ReturnType<typeof reviewGetById>>,
	TError = ErrorType<ProblemDetails | void>,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof reviewGetById>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof reviewGetById>>,
					TError,
					Awaited<ReturnType<typeof reviewGetById>>
				>,
				'initialData'
			>;
		request?: SecondParameter<typeof axiosInstance>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useReviewGetById<
	TData = Awaited<ReturnType<typeof reviewGetById>>,
	TError = ErrorType<ProblemDetails | void>,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof reviewGetById>>, TError, TData>
		>;
		request?: SecondParameter<typeof axiosInstance>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};

export function useReviewGetById<
	TData = Awaited<ReturnType<typeof reviewGetById>>,
	TError = ErrorType<ProblemDetails | void>,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof reviewGetById>>, TError, TData>
		>;
		request?: SecondParameter<typeof axiosInstance>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getReviewGetByIdQueryOptions(id, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

export const reviewDelete = (
	id: string,
	options?: SecondParameter<typeof axiosInstance>,
	signal?: AbortSignal
) => {
	return axiosInstance<ReviewResponse>(
		{ url: `/Review/${id}`, method: 'DELETE', signal },
		options
	);
};

export const getReviewDeleteMutationOptions = <
	TError = ErrorType<ProblemDetails | void>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof reviewDelete>>,
		TError,
		{ id: string },
		TContext
	>;
	request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof reviewDelete>>,
	TError,
	{ id: string },
	TContext
> => {
	const mutationKey = ['reviewDelete'];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			'mutationKey' in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof reviewDelete>>,
		{ id: string }
	> = props => {
		const { id } = props ?? {};

		return reviewDelete(id, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type ReviewDeleteMutationResult = NonNullable<
	Awaited<ReturnType<typeof reviewDelete>>
>;

export type ReviewDeleteMutationError = ErrorType<ProblemDetails | void>;

export const useReviewDelete = <
	TError = ErrorType<ProblemDetails | void>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof reviewDelete>>,
			TError,
			{ id: string },
			TContext
		>;
		request?: SecondParameter<typeof axiosInstance>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof reviewDelete>>,
	TError,
	{ id: string },
	TContext
> => {
	return useMutation(getReviewDeleteMutationOptions(options), queryClient);
};
export const reviewGetByProductId = (
	id: string,
	options?: SecondParameter<typeof axiosInstance>,
	signal?: AbortSignal
) => {
	return axiosInstance<ReviewResponse[]>(
		{ url: `/Review/getProductReviews/${id}`, method: 'GET', signal },
		options
	);
};

export const getReviewGetByProductIdQueryKey = (id: string) => {
	return [`/Review/getProductReviews/${id}`] as const;
};

export const getReviewGetByProductIdQueryOptions = <
	TData = Awaited<ReturnType<typeof reviewGetByProductId>>,
	TError = ErrorType<ProblemDetails | void>,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof reviewGetByProductId>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof axiosInstance>;
	}
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getReviewGetByProductIdQueryKey(id);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof reviewGetByProductId>>
	> = ({ signal }) => reviewGetByProductId(id, requestOptions, signal);

	return {
		queryKey,
		queryFn,
		enabled: !!id,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof reviewGetByProductId>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ReviewGetByProductIdQueryResult = NonNullable<
	Awaited<ReturnType<typeof reviewGetByProductId>>
>;
export type ReviewGetByProductIdQueryError = ErrorType<ProblemDetails | void>;

export function useReviewGetByProductId<
	TData = Awaited<ReturnType<typeof reviewGetByProductId>>,
	TError = ErrorType<ProblemDetails | void>,
>(
	id: string,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof reviewGetByProductId>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof reviewGetByProductId>>,
					TError,
					Awaited<ReturnType<typeof reviewGetByProductId>>
				>,
				'initialData'
			>;
		request?: SecondParameter<typeof axiosInstance>;
	},
	queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useReviewGetByProductId<
	TData = Awaited<ReturnType<typeof reviewGetByProductId>>,
	TError = ErrorType<ProblemDetails | void>,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof reviewGetByProductId>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof reviewGetByProductId>>,
					TError,
					Awaited<ReturnType<typeof reviewGetByProductId>>
				>,
				'initialData'
			>;
		request?: SecondParameter<typeof axiosInstance>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useReviewGetByProductId<
	TData = Awaited<ReturnType<typeof reviewGetByProductId>>,
	TError = ErrorType<ProblemDetails | void>,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof reviewGetByProductId>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof axiosInstance>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};

export function useReviewGetByProductId<
	TData = Awaited<ReturnType<typeof reviewGetByProductId>>,
	TError = ErrorType<ProblemDetails | void>,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof reviewGetByProductId>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof axiosInstance>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getReviewGetByProductIdQueryOptions(id, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}
