/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Demo API
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from '@tanstack/react-query';

import type {
	ProblemDetails,
	ProductCreateBody,
	ProductGetPagedParams,
	ProductPatchBody,
	ProductResponse,
	ProductResponsePageOfResponse,
} from '.././model';

import { axiosInstance } from '../../axiosInstance';
import type { ErrorType, BodyType } from '../../axiosInstance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const productGetPaged = (
	params?: ProductGetPagedParams,
	options?: SecondParameter<typeof axiosInstance>,
	signal?: AbortSignal
) => {
	return axiosInstance<ProductResponsePageOfResponse>(
		{ url: `/Product`, method: 'GET', params, signal },
		options
	);
};

export const getProductGetPagedQueryKey = (params?: ProductGetPagedParams) => {
	return [`/Product`, ...(params ? [params] : [])] as const;
};

export const getProductGetPagedQueryOptions = <
	TData = Awaited<ReturnType<typeof productGetPaged>>,
	TError = ErrorType<void>,
>(
	params?: ProductGetPagedParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof productGetPaged>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof axiosInstance>;
	}
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getProductGetPagedQueryKey(params);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof productGetPaged>>> = ({
		signal,
	}) => productGetPaged(params, requestOptions, signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof productGetPaged>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ProductGetPagedQueryResult = NonNullable<
	Awaited<ReturnType<typeof productGetPaged>>
>;
export type ProductGetPagedQueryError = ErrorType<void>;

export function useProductGetPaged<
	TData = Awaited<ReturnType<typeof productGetPaged>>,
	TError = ErrorType<void>,
>(
	params: undefined | ProductGetPagedParams,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof productGetPaged>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof productGetPaged>>,
					TError,
					Awaited<ReturnType<typeof productGetPaged>>
				>,
				'initialData'
			>;
		request?: SecondParameter<typeof axiosInstance>;
	},
	queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useProductGetPaged<
	TData = Awaited<ReturnType<typeof productGetPaged>>,
	TError = ErrorType<void>,
>(
	params?: ProductGetPagedParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof productGetPaged>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof productGetPaged>>,
					TError,
					Awaited<ReturnType<typeof productGetPaged>>
				>,
				'initialData'
			>;
		request?: SecondParameter<typeof axiosInstance>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useProductGetPaged<
	TData = Awaited<ReturnType<typeof productGetPaged>>,
	TError = ErrorType<void>,
>(
	params?: ProductGetPagedParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof productGetPaged>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof axiosInstance>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};

export function useProductGetPaged<
	TData = Awaited<ReturnType<typeof productGetPaged>>,
	TError = ErrorType<void>,
>(
	params?: ProductGetPagedParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof productGetPaged>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof axiosInstance>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getProductGetPagedQueryOptions(params, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

export const productCreate = (
	productCreateBody: BodyType<ProductCreateBody>,
	options?: SecondParameter<typeof axiosInstance>,
	signal?: AbortSignal
) => {
	const formData = new FormData();
	formData.append(`Name`, productCreateBody.Name);
	formData.append(`Description`, productCreateBody.Description);
	formData.append(`Category`, productCreateBody.Category);
	if (productCreateBody.Image !== undefined) {
		formData.append(`Image`, productCreateBody.Image);
	}
	formData.append(`Price`, productCreateBody.Price.toString());
	formData.append(`Stock`, productCreateBody.Stock.toString());

	return axiosInstance<ProductResponse>(
		{
			url: `/Product`,
			method: 'POST',
			headers: { 'Content-Type': 'multipart/form-data' },
			data: formData,
			signal,
		},
		options
	);
};

export const getProductCreateMutationOptions = <
	TError = ErrorType<ProblemDetails | void>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof productCreate>>,
		TError,
		{ data: BodyType<ProductCreateBody> },
		TContext
	>;
	request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof productCreate>>,
	TError,
	{ data: BodyType<ProductCreateBody> },
	TContext
> => {
	const mutationKey = ['productCreate'];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			'mutationKey' in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof productCreate>>,
		{ data: BodyType<ProductCreateBody> }
	> = props => {
		const { data } = props ?? {};

		return productCreate(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type ProductCreateMutationResult = NonNullable<
	Awaited<ReturnType<typeof productCreate>>
>;
export type ProductCreateMutationBody = BodyType<ProductCreateBody>;
export type ProductCreateMutationError = ErrorType<ProblemDetails | void>;

export const useProductCreate = <
	TError = ErrorType<ProblemDetails | void>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof productCreate>>,
			TError,
			{ data: BodyType<ProductCreateBody> },
			TContext
		>;
		request?: SecondParameter<typeof axiosInstance>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof productCreate>>,
	TError,
	{ data: BodyType<ProductCreateBody> },
	TContext
> => {
	return useMutation(getProductCreateMutationOptions(options), queryClient);
};
export const productGetById = (
	id: string,
	options?: SecondParameter<typeof axiosInstance>,
	signal?: AbortSignal
) => {
	return axiosInstance<ProductResponse>(
		{ url: `/Product/${id}`, method: 'GET', signal },
		options
	);
};

export const getProductGetByIdQueryKey = (id: string) => {
	return [`/Product/${id}`] as const;
};

export const getProductGetByIdQueryOptions = <
	TData = Awaited<ReturnType<typeof productGetById>>,
	TError = ErrorType<ProblemDetails | void>,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof productGetById>>, TError, TData>
		>;
		request?: SecondParameter<typeof axiosInstance>;
	}
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getProductGetByIdQueryKey(id);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof productGetById>>> = ({
		signal,
	}) => productGetById(id, requestOptions, signal);

	return {
		queryKey,
		queryFn,
		enabled: !!id,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof productGetById>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ProductGetByIdQueryResult = NonNullable<
	Awaited<ReturnType<typeof productGetById>>
>;
export type ProductGetByIdQueryError = ErrorType<ProblemDetails | void>;

export function useProductGetById<
	TData = Awaited<ReturnType<typeof productGetById>>,
	TError = ErrorType<ProblemDetails | void>,
>(
	id: string,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof productGetById>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof productGetById>>,
					TError,
					Awaited<ReturnType<typeof productGetById>>
				>,
				'initialData'
			>;
		request?: SecondParameter<typeof axiosInstance>;
	},
	queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useProductGetById<
	TData = Awaited<ReturnType<typeof productGetById>>,
	TError = ErrorType<ProblemDetails | void>,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof productGetById>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof productGetById>>,
					TError,
					Awaited<ReturnType<typeof productGetById>>
				>,
				'initialData'
			>;
		request?: SecondParameter<typeof axiosInstance>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useProductGetById<
	TData = Awaited<ReturnType<typeof productGetById>>,
	TError = ErrorType<ProblemDetails | void>,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof productGetById>>, TError, TData>
		>;
		request?: SecondParameter<typeof axiosInstance>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};

export function useProductGetById<
	TData = Awaited<ReturnType<typeof productGetById>>,
	TError = ErrorType<ProblemDetails | void>,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof productGetById>>, TError, TData>
		>;
		request?: SecondParameter<typeof axiosInstance>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getProductGetByIdQueryOptions(id, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

export const productPatch = (
	id: string,
	productPatchBody: BodyType<ProductPatchBody>,
	options?: SecondParameter<typeof axiosInstance>,
	signal?: AbortSignal
) => {
	const formData = new FormData();
	if (productPatchBody.Name !== undefined) {
		formData.append(`Name`, productPatchBody.Name);
	}
	if (productPatchBody.Description !== undefined) {
		formData.append(`Description`, productPatchBody.Description);
	}
	if (productPatchBody.Category !== undefined) {
		formData.append(`Category`, productPatchBody.Category);
	}
	if (productPatchBody['Image.HasValue'] !== undefined) {
		formData.append(
			`Image.HasValue`,
			productPatchBody['Image.HasValue'].toString()
		);
	}
	if (productPatchBody['Image.Value'] !== undefined) {
		formData.append(`Image.Value`, productPatchBody['Image.Value']);
	}
	if (productPatchBody.Price !== undefined) {
		formData.append(`Price`, productPatchBody.Price.toString());
	}
	if (productPatchBody.Stock !== undefined) {
		formData.append(`Stock`, productPatchBody.Stock.toString());
	}

	return axiosInstance<void>(
		{
			url: `/Product/${id}`,
			method: 'PATCH',
			headers: { 'Content-Type': 'multipart/form-data' },
			data: formData,
			signal,
		},
		options
	);
};

export const getProductPatchMutationOptions = <
	TError = ErrorType<ProblemDetails | void>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof productPatch>>,
		TError,
		{ id: string; data: BodyType<ProductPatchBody> },
		TContext
	>;
	request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof productPatch>>,
	TError,
	{ id: string; data: BodyType<ProductPatchBody> },
	TContext
> => {
	const mutationKey = ['productPatch'];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			'mutationKey' in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof productPatch>>,
		{ id: string; data: BodyType<ProductPatchBody> }
	> = props => {
		const { id, data } = props ?? {};

		return productPatch(id, data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type ProductPatchMutationResult = NonNullable<
	Awaited<ReturnType<typeof productPatch>>
>;
export type ProductPatchMutationBody = BodyType<ProductPatchBody>;
export type ProductPatchMutationError = ErrorType<ProblemDetails | void>;

export const useProductPatch = <
	TError = ErrorType<ProblemDetails | void>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof productPatch>>,
			TError,
			{ id: string; data: BodyType<ProductPatchBody> },
			TContext
		>;
		request?: SecondParameter<typeof axiosInstance>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof productPatch>>,
	TError,
	{ id: string; data: BodyType<ProductPatchBody> },
	TContext
> => {
	return useMutation(getProductPatchMutationOptions(options), queryClient);
};
export const productDelete = (
	id: string,
	options?: SecondParameter<typeof axiosInstance>,
	signal?: AbortSignal
) => {
	return axiosInstance<void>(
		{ url: `/Product/${id}`, method: 'DELETE', signal },
		options
	);
};

export const getProductDeleteMutationOptions = <
	TError = ErrorType<ProblemDetails | void>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof productDelete>>,
		TError,
		{ id: string },
		TContext
	>;
	request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof productDelete>>,
	TError,
	{ id: string },
	TContext
> => {
	const mutationKey = ['productDelete'];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			'mutationKey' in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof productDelete>>,
		{ id: string }
	> = props => {
		const { id } = props ?? {};

		return productDelete(id, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type ProductDeleteMutationResult = NonNullable<
	Awaited<ReturnType<typeof productDelete>>
>;

export type ProductDeleteMutationError = ErrorType<ProblemDetails | void>;

export const useProductDelete = <
	TError = ErrorType<ProblemDetails | void>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof productDelete>>,
			TError,
			{ id: string },
			TContext
		>;
		request?: SecondParameter<typeof axiosInstance>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof productDelete>>,
	TError,
	{ id: string },
	TContext
> => {
	return useMutation(getProductDeleteMutationOptions(options), queryClient);
};
