/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Demo API
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from '@tanstack/react-query';

import type {
	ProblemDetails,
	ProductRequest,
	ProductResponse,
} from '.././model';

import { axiosInstance } from '../../axiosInstance';
import type { ErrorType, BodyType } from '../../axiosInstance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const productGetAll = (
	options?: SecondParameter<typeof axiosInstance>,
	signal?: AbortSignal
) => {
	return axiosInstance<ProductResponse[]>(
		{ url: `/Product`, method: 'GET', signal },
		options
	);
};

export const getProductGetAllQueryKey = () => {
	return [`/Product`] as const;
};

export const getProductGetAllQueryOptions = <
	TData = Awaited<ReturnType<typeof productGetAll>>,
	TError = ErrorType<void>,
>(options?: {
	query?: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof productGetAll>>, TError, TData>
	>;
	request?: SecondParameter<typeof axiosInstance>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getProductGetAllQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof productGetAll>>> = ({
		signal,
	}) => productGetAll(requestOptions, signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof productGetAll>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ProductGetAllQueryResult = NonNullable<
	Awaited<ReturnType<typeof productGetAll>>
>;
export type ProductGetAllQueryError = ErrorType<void>;

export function useProductGetAll<
	TData = Awaited<ReturnType<typeof productGetAll>>,
	TError = ErrorType<void>,
>(
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof productGetAll>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof productGetAll>>,
					TError,
					Awaited<ReturnType<typeof productGetAll>>
				>,
				'initialData'
			>;
		request?: SecondParameter<typeof axiosInstance>;
	},
	queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useProductGetAll<
	TData = Awaited<ReturnType<typeof productGetAll>>,
	TError = ErrorType<void>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof productGetAll>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof productGetAll>>,
					TError,
					Awaited<ReturnType<typeof productGetAll>>
				>,
				'initialData'
			>;
		request?: SecondParameter<typeof axiosInstance>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useProductGetAll<
	TData = Awaited<ReturnType<typeof productGetAll>>,
	TError = ErrorType<void>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof productGetAll>>, TError, TData>
		>;
		request?: SecondParameter<typeof axiosInstance>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};

export function useProductGetAll<
	TData = Awaited<ReturnType<typeof productGetAll>>,
	TError = ErrorType<void>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof productGetAll>>, TError, TData>
		>;
		request?: SecondParameter<typeof axiosInstance>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getProductGetAllQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

export const productCreate = (
	productRequest: BodyType<ProductRequest>,
	options?: SecondParameter<typeof axiosInstance>,
	signal?: AbortSignal
) => {
	return axiosInstance<ProductResponse>(
		{
			url: `/Product`,
			method: 'POST',
			headers: { 'Content-Type': 'application/json' },
			data: productRequest,
			signal,
		},
		options
	);
};

export const getProductCreateMutationOptions = <
	TError = ErrorType<ProblemDetails | void>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof productCreate>>,
		TError,
		{ data: BodyType<ProductRequest> },
		TContext
	>;
	request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof productCreate>>,
	TError,
	{ data: BodyType<ProductRequest> },
	TContext
> => {
	const mutationKey = ['productCreate'];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			'mutationKey' in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof productCreate>>,
		{ data: BodyType<ProductRequest> }
	> = props => {
		const { data } = props ?? {};

		return productCreate(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type ProductCreateMutationResult = NonNullable<
	Awaited<ReturnType<typeof productCreate>>
>;
export type ProductCreateMutationBody = BodyType<ProductRequest>;
export type ProductCreateMutationError = ErrorType<ProblemDetails | void>;

export const useProductCreate = <
	TError = ErrorType<ProblemDetails | void>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof productCreate>>,
			TError,
			{ data: BodyType<ProductRequest> },
			TContext
		>;
		request?: SecondParameter<typeof axiosInstance>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof productCreate>>,
	TError,
	{ data: BodyType<ProductRequest> },
	TContext
> => {
	return useMutation(getProductCreateMutationOptions(options), queryClient);
};
export const productGetById = (
	id: string,
	options?: SecondParameter<typeof axiosInstance>,
	signal?: AbortSignal
) => {
	return axiosInstance<ProductResponse>(
		{ url: `/Product/${id}`, method: 'GET', signal },
		options
	);
};

export const getProductGetByIdQueryKey = (id: string) => {
	return [`/Product/${id}`] as const;
};

export const getProductGetByIdQueryOptions = <
	TData = Awaited<ReturnType<typeof productGetById>>,
	TError = ErrorType<ProblemDetails | void>,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof productGetById>>, TError, TData>
		>;
		request?: SecondParameter<typeof axiosInstance>;
	}
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getProductGetByIdQueryKey(id);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof productGetById>>> = ({
		signal,
	}) => productGetById(id, requestOptions, signal);

	return {
		queryKey,
		queryFn,
		enabled: !!id,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof productGetById>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ProductGetByIdQueryResult = NonNullable<
	Awaited<ReturnType<typeof productGetById>>
>;
export type ProductGetByIdQueryError = ErrorType<ProblemDetails | void>;

export function useProductGetById<
	TData = Awaited<ReturnType<typeof productGetById>>,
	TError = ErrorType<ProblemDetails | void>,
>(
	id: string,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof productGetById>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof productGetById>>,
					TError,
					Awaited<ReturnType<typeof productGetById>>
				>,
				'initialData'
			>;
		request?: SecondParameter<typeof axiosInstance>;
	},
	queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useProductGetById<
	TData = Awaited<ReturnType<typeof productGetById>>,
	TError = ErrorType<ProblemDetails | void>,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof productGetById>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof productGetById>>,
					TError,
					Awaited<ReturnType<typeof productGetById>>
				>,
				'initialData'
			>;
		request?: SecondParameter<typeof axiosInstance>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useProductGetById<
	TData = Awaited<ReturnType<typeof productGetById>>,
	TError = ErrorType<ProblemDetails | void>,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof productGetById>>, TError, TData>
		>;
		request?: SecondParameter<typeof axiosInstance>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};

export function useProductGetById<
	TData = Awaited<ReturnType<typeof productGetById>>,
	TError = ErrorType<ProblemDetails | void>,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof productGetById>>, TError, TData>
		>;
		request?: SecondParameter<typeof axiosInstance>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getProductGetByIdQueryOptions(id, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

export const productDelete = (
	id: string,
	options?: SecondParameter<typeof axiosInstance>,
	signal?: AbortSignal
) => {
	return axiosInstance<void>(
		{ url: `/Product/${id}`, method: 'DELETE', signal },
		options
	);
};

export const getProductDeleteMutationOptions = <
	TError = ErrorType<ProblemDetails | void>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof productDelete>>,
		TError,
		{ id: string },
		TContext
	>;
	request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof productDelete>>,
	TError,
	{ id: string },
	TContext
> => {
	const mutationKey = ['productDelete'];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			'mutationKey' in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof productDelete>>,
		{ id: string }
	> = props => {
		const { id } = props ?? {};

		return productDelete(id, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type ProductDeleteMutationResult = NonNullable<
	Awaited<ReturnType<typeof productDelete>>
>;

export type ProductDeleteMutationError = ErrorType<ProblemDetails | void>;

export const useProductDelete = <
	TError = ErrorType<ProblemDetails | void>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof productDelete>>,
			TError,
			{ id: string },
			TContext
		>;
		request?: SecondParameter<typeof axiosInstance>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof productDelete>>,
	TError,
	{ id: string },
	TContext
> => {
	return useMutation(getProductDeleteMutationOptions(options), queryClient);
};
