/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Demo API
 * OpenAPI spec version: v1
 */

export interface AddressRequiredDto {
	/** @minLength 1 */
	city: string;
	/** @minLength 1 */
	street: string;
	/** @minLength 1 */
	houseNumber: string;
}
