/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Demo API
 * OpenAPI spec version: v1
 */

export interface AddressDto {
	/** @nullable */
	city?: string | null;
	/** @nullable */
	street?: string | null;
	/** @nullable */
	houseNumber?: string | null;
}
