/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Demo API
 * OpenAPI spec version: v1
 */
import type { ObjectId } from './objectId';

export interface OrderItem {
	productId: ObjectId;
	/** @nullable */
	nameAtOrder: string | null;
	priceAtOrder: number;
	quantity: number;
}
