/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Demo API
 * OpenAPI spec version: v1
 */
import type { AddressDto } from './addressDto';
import type { OrderItemRequest } from './orderItemRequest';

export interface OrderRequest {
	/** @minLength 1 */
	userId: string;
	items: OrderItemRequest[];
	address: AddressDto;
}
