/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Demo API
 * OpenAPI spec version: v1
 */

export interface OrderReviewItem {
	/** @minLength 1 */
	productId: string;
	/** @minLength 1 */
	productName: string;
	/** @nullable */
	imageUrl?: string | null;
	unitPrice: number;
	quantity: number;
	stock: number;
	lineTotal: number;
}
