/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Demo API
 * OpenAPI spec version: v1
 */
import type { OrderItemRequest } from './orderItemRequest';

export interface OrderReviewRequest {
	items: OrderItemRequest[];
}
