/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Demo API
 * OpenAPI spec version: v1
 */
import type { Address } from './address';
import type { ObjectId } from './objectId';
import type { OrderItem } from './orderItem';

export interface OrderResponse {
	id: ObjectId;
	userId: ObjectId;
	items: OrderItem[];
	address: Address;
	price: number;
	placedAt: string;
}
