/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Demo API
 * OpenAPI spec version: v1
 */
import type { OrderReviewItem } from './orderReviewItem';

export interface OrderReviewResponse {
	items: OrderReviewItem[];
	total: number;
}
