/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Demo API
 * OpenAPI spec version: v1
 */

export interface OrderItemRequest {
	/** @minLength 1 */
	productId: string;
	quantity: number;
}
