/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Demo API
 * OpenAPI spec version: v1
 */

export interface PatchProductRequest {
	/** @nullable */
	name?: string | null;
	/** @nullable */
	category?: string | null;
	/** @nullable */
	image?: string | null;
	/** @nullable */
	price?: number | null;
}
