/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Demo API
 * OpenAPI spec version: v1
 */

export interface ProblemDetails {
	/** @nullable */
	type?: string | null;
	/** @nullable */
	title?: string | null;
	/** @nullable */
	status?: number | null;
	/** @nullable */
	detail?: string | null;
	/** @nullable */
	instance?: string | null;
	[key: string]: unknown;
}
