/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Demo API
 * OpenAPI spec version: v1
 */
import type { ProductImageResponse } from './productImageResponse';

export interface ProductResponse {
	/** @minLength 1 */
	id: string;
	/** @minLength 1 */
	name: string;
	/** @minLength 1 */
	category: string;
	image?: ProductImageResponse;
	price: number;
	averageRating: number;
}
