/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Demo API
 * OpenAPI spec version: v1
 */

export type ProductGetPagedParams = {
	PageSize?: number;
	Page?: number;
	Search?: string;
	Category?: string;
	MinPrice?: number;
	MaxPrice?: number;
	MinRating?: number;
	InStockOnly?: boolean;
};
