/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Demo API
 * OpenAPI spec version: v1
 */

export type ProductCreateBody = {
	Name: string;
	Category: string;
	Image?: Blob;
	Price: number;
};
