/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Demo API
 * OpenAPI spec version: v1
 */

export type ProductPatchBody = {
	Name?: string;
	Category?: string;
	'Image.HasValue'?: boolean;
	'Image.Value'?: Blob;
	Price?: number;
};
