/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Demo API
 * OpenAPI spec version: v1
 */

export interface ProductRequest {
	/** @minLength 1 */
	name: string;
	/** @minLength 1 */
	category: string;
	/** @minLength 1 */
	image: string;
	price: number;
}
