/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Demo API
 * OpenAPI spec version: v1
 */
import type { ObjectId } from './objectId';

export interface ProductResponse {
	id: ObjectId;
	/** @minLength 1 */
	name: string;
	/** @minLength 1 */
	category: string;
	/** @nullable */
	image?: string | null;
	price: number;
}
