/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Demo API
 * OpenAPI spec version: v1
 */

export interface ProductResponse {
	/** @minLength 1 */
	id: string;
	/** @minLength 1 */
	name: string;
	/** @minLength 1 */
	description: string;
	/** @minLength 1 */
	category: string;
	/** @nullable */
	thumbnailUrl?: string | null;
	averageRating: number;
	reviewCount: number;
	price: number;
	stock: number;
}
