/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Demo API
 * OpenAPI spec version: v1
 */
import type { ProductResponse } from './productResponse';

export interface ProductResponsePageOfResponse {
	items: ProductResponse[];
	page: number;
	pageSize: number;
	totalItems: number;
	readonly totalPages: number;
	readonly hasNextPage: boolean;
	readonly hasPreviousPage: boolean;
}
