/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Demo API
 * OpenAPI spec version: v1
 */

export interface ProductImageResponse {
	/** @minLength 1 */
	publicId: string;
	/** @minLength 1 */
	url: string;
	isThumbnail: boolean;
	order: number;
}
