/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Demo API
 * OpenAPI spec version: v1
 */

export interface RegisterUser {
	/** @minLength 1 */
	name: string;
	/** @minLength 1 */
	surname: string;
	/** @minLength 1 */
	email: string;
	/** @minLength 1 */
	password: string;
}
