/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Demo API
 * OpenAPI spec version: v1
 */

export interface ReviewResponse {
	/** @minLength 1 */
	id: string;
	/** @minLength 1 */
	userId: string;
	/** @minLength 1 */
	userFullName: string;
	/** @minLength 1 */
	productId: string;
	rating: number;
	/** @minLength 1 */
	description: string;
}
