/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Demo API
 * OpenAPI spec version: v1
 */
import type { ObjectId } from './objectId';

export interface ReviewResponse {
	id: ObjectId;
	userId: ObjectId;
	productId: ObjectId;
	rating: number;
	/** @minLength 1 */
	description: string;
}
