/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Demo API
 * OpenAPI spec version: v1
 */
import type { AddressDto } from './addressDto';

export interface UpdateUserRequest {
	/** @minLength 1 */
	name: string;
	/** @minLength 1 */
	surname: string;
	address?: AddressDto;
}
