/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Demo API
 * OpenAPI spec version: v1
 */
import type { AddressDto } from './addressDto';

export interface UserResponse {
	/** @minLength 1 */
	id: string;
	/** @minLength 1 */
	name: string;
	/** @minLength 1 */
	surname: string;
	/** @minLength 1 */
	email: string;
	address: AddressDto;
}
