/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Demo API
 * OpenAPI spec version: v1
 */
import type { Address } from './address';
import type { ObjectId } from './objectId';

export interface UserResponse {
	id: ObjectId;
	/** @minLength 1 */
	name: string;
	/** @minLength 1 */
	surname: string;
	/** @minLength 1 */
	email: string;
	address: Address;
}
